### ISSUE TITLE
ModuleNotFoundError: No module named 'tgx.io.read_files'! Can you please upload this module?

### ISSUE THREAD

**Issue by HorHang** [fpour/TGX#20]
![image](https://github.com/ComplexData-MILA/TGX/assets/103940969/0bb180c5-5cc0-4b73-87a0-931b893ec0dc)

![image](https://github.com/ComplexData-MILA/TGX/assets/103940969/5526f986-0af2-4df6-a61b-69cf94cb9d24)

**Comment by shenyangHuang** [comment]
Hi, 

Thanks for your interest in our work. This project is undergoing active development thus syntax and usage might change until a stable version is reached. Please see the [starting example](https://github.com/ComplexData-MILA/TGX/blob/master/starting_example.py) to start. 

Best,
Andy

**Comment by HorHang** [comment]
Thanks, Huang! I hope the stable version will be released soon. Thanks for your effort and contribution.
