### ISSUE TITLE
The Specified Version of `geoopt` Is Not Found

### ISSUE THREAD

**Issue by Aydin62** [fpour/TGX#33]
Hi. When trying
```
pip install geoopt==0.5.1
```
it complains:

_ERROR: Could not find a version that satisfies the requirement geoopt==0.5.1 (from versions: 0.0.1rc2, 0.0.1, 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.3.0, 0.3.1, 0.4.0rc1, 0.4.0, 0.4.1, 0.5.0)
ERROR: No matching distribution found for geoopt==0.5.1_

**Comment by Aydin62** [comment]
From the above list of available versions, I suppose the best match would be 0.5.0.

Does this version satisfy the requirements of `TGX`?

**Comment by shenyangHuang** [comment]
`geoopt` dependency removed as it is not directly used in the package
