### ISSUE TITLE
`venv` Command Syntax Correction Needed

### ISSUE THREAD

**Issue by Aydin62** [fpour/TGX#36]
At Step 1 of installation, it is instructed to enter these commands:

```
python -m venv ~/tgx_env/
source ~/tgx_env/bin/activate
```

However, as the parent folder is supposed to be `TGX` and not `~`, the above commands should be modified as:

```
python -m venv ./tgx_env/
source ./tgx_env/bin/activate
```

That is, to replace the tildes (`~`) with single dots (`.`) in both lines.

**Comment by shenyangHuang** [comment]
read me updated
