### ISSUE TITLE
To Make `TGX` Google-Colab-Friendly

### ISSUE THREAD

**Issue by Aydin62** [fpour/TGX#37]
I tried to install `TGX` on Google Colab, but it complained on line 36 of `requirements.txt`:

```
-e git+ssh://git@github.com/ComplexData-MILA/TGX.git@bf47a2946ef35c5f96ba8cbe9c3e397d39c5e58e#egg=py_tgx
```

Can this be converted into something more compatible with Colab?

**Comment by Aydin62** [comment]
![Screenshot from 2024-02-17 21-15-56](https://github.com/ComplexData-MILA/TGX/assets/44974419/0b57ee96-2de2-483a-ae38-4359b97b1668)

**Comment by Aydin62** [comment]
Even tried to duplicate the repository on my own account, with line 36 modified as replacing my own address and key, but got the same error again...

**Comment by shenyangHuang** [comment]
please try again with the new version, thanks Aydin.

**Comment by Aydin62** [comment]
I was able to complete the installation process, but I couldn't import the package and use it.

For example, in the tutorial, it is done this way:

```
import tgx
```

However, when I enter this, it complains that no such module exists! And if do it as either
```
import py_tgx
```
or
```
import pytgx
```
again, the same error. Please include the correct way to import and use the package within ReadMe. Thanks.


BTW, please correct these minor typos in the ReadMe:

Step 5. [Aternative] --> [Alternative]

Step 6. [optional] --> [Optional]

**Comment by fpour** [comment]
Thanks for following up on the issue.
Regarding the installation, I'm unable to reproduce the issue you mentioned.
Basically, what you need to do is as follows (considering that you want to use TGX in a colab notebook):

1. `!pip install py-tgx`
2. `import tgx`
3. Any intended functionalities...

As you can see in the attachment, it should work just fine in colab.
Please let us know if there's more issue.

![image](https://github.com/ComplexData-MILA/TGX/assets/12398091/6f8735fb-97d9-4a75-9909-3b007123e764)


[PS: Thanks for spotting the typos, it will be updated soon!]

**Comment by Aydin62** [comment]
Yes, I tried again today and it works fine now!

Not sure what exactly had caused yesterday's failure! :))
