### ISSUE TITLE
Conflicting Dependencies

### ISSUE THREAD

**Issue by Aydin62** [fpour/TGX#38]
Tried to bypass the previous issues and install `TGX` both locally and on Google Colab. In both cases, the installation progress was aborted due to conflicting dependencies.

Here is a snapshot of the local one:

![local-dep](https://github.com/ComplexData-MILA/TGX/assets/44974419/93216bb8-d0db-4d77-911a-fe680ab644d7)

And here is the Colab one:

![colab-dep](https://github.com/ComplexData-MILA/TGX/assets/44974419/530104fa-fad4-4bcf-8f16-6b28c82b18fe)

**Comment by shenyangHuang** [comment]
unnecessary dependencies removed
