### ISSUE TITLE
Remove the Deprecated `sklearn` Package Dependency

### ISSUE THREAD

**Issue by Aydin62** [fpour/TGX#40]
While installing, got the following error:

![sklearn](https://github.com/ComplexData-MILA/TGX/assets/44974419/50c80be6-c1bc-4fed-99b9-821c06d4c26b)

As `scikit-learn` is already listed as a dependency, as I guess, there is no need for the deprecated package `sklearn` anymore, and it can be removed from `requirements.txt`.

**Comment by shenyangHuang** [comment]
yes, `requirements.txt` updated
